name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ' New Features'
    labels:
      - 'type:major_features'
      - 'type:minor_features'

  - title: ' Bugs Fixes'
    labels:
      - 'type:fix'

  - title: ' Documentation'
    labels:
      - 'type:documentation'

  - title: ' Configuration'
    labels:
      - 'type:config'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

version-resolver:
  major:
    labels:
      - 'type:major_features'
  minor:
    labels:
      - 'type:minor_features'
  patch:
    labels:
      - 'type:fix'
      - 'type:documentation'
      - 'type:config'
      - 'type:tests'
