name: Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build_type:
        description: "Build type: Debug, Release"
        type: string
        required: false
        default: "Release"
      build_dir:
        description: "Build directory"
        type: string
        required: false
        default: "build"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_DIR: ${{ inputs.build_dir }}
  BUILD_TYPE: ${{ inputs.build_type }}
  CCACHE_BASEDIR: $GITHUB_WORKSPACE
  CCACHE_DIR: $GITHUB_WORKSPACE/.ccache
  CCACHE_COMPRESS: "true"
  CCACHE_COMPRESSLEVEL: "6"
  CCACHE_MAXSIZE: "400M"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Apt update
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update

      - name: Set up GCC
        run: |
          sudo apt install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 20 --slave /usr/bin/g++ g++ /usr/bin/g++-13

      - name: Install static and dynamic checkers
        run: |
          sudo apt install -y clang-format
          sudo apt install -y clang-tidy
          sudo apt install -y iwyu
          sudo apt install -y valgrind

      - name: Install doxygen
        run: |
          sudo apt install -y doxygen graphviz

      - name: Install ccache
        run: sudo apt install -y ccache

      - name: Cache boost
        uses: actions/cache@v3
        id: cache-boost
        with:
          path: "~/boost"
          key: ${{ runner.os }}-build-boost

      - name: Install boost
        env:
          CACHE_HIT: ${{ steps.cache-boost.outputs.cache-hit }}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --force --recursive ~/boost/lib/* /usr/lib
            sudo cp --force --recursive ~/boost/include/* /usr/include/boost
          else
            wget https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.gz
            tar -xzf boost_*.tar.gz
            cd boost_1_83_0
            sudo ./bootstrap.sh
            sudo ./b2 install  
            mkdir ~/boost
            mkdir ~/boost/lib
            mkdir ~/boost/include
            sudo cp --force --recursive /usr/local/lib/libboost* ~/boost/lib
            sudo cp --force --recursive /usr/local/include/boost ~/boost/include
          fi

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: |
          current_date=`date "+%Y-%m-%d-%H;%M;%S"`
          echo "timestamp=${current_date}" >> $GITHUB_OUTPUT

      - name: ccache cache files
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Zero the cache statistics
        run: |
          ccache -p
          ccache -z

      - name: Configure CMake
        run: cmake -S . -B $BUILD_DIR -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build ./$BUILD_DIR -j 2

      - name: ccache statistics
        run: ccache -s

      - name: Make build archive
        run: tar -czf $BUILD_DIR.tar.gz $BUILD_DIR

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.build_dir }}
          path: ${{ inputs.build_dir }}.tar.gz
